#!/bin/sh
[ $# -lt 2 ] && {
	>&2 cat <<-EOT
	alarm 40 Wash, check towels
	alarm 1500 Make a phone call, to the bank
	EOT
	exit 1
}
ts="$1"; shift
case "$ts" in
	now)
		;;
	?|??|???)
		ts="now + $ts minutes"
		;;
esac
text="$*,"
summary="${text%%,*}"
body="${text#*,}"
body="${body%,}"
cmd="notify-send -u critical '$summary' '$body'"
future="$(echo "$cmd" | at -v "$ts" 2>&1 | sponge | head -n 1)"
if [ "$ts" != 'now' ]; then
	cat >> ~/todo <<-EOF

	[$future]
	$*
	EOF
fi
